echo "The number of arguments passed from CLI $#"
echo "Show all the argument $*"
echo "Show Last command executed Status $?"
echo "IP Address=$2"
echo "Show Last Argument Passed $_"
echo "Show Script File Name $0"
